config/routes.rb
Rails.application.routes.draw do
  # after we ran a --   rails g controller Topics index show   it generated these routes
  # get 'topics/index'
  # get 'topics/show'

  # we are changing it to this route
  resources :topics, only: [:index, :show]

  devise_for :users
  # default routes given to us for resources  
  # resources :portfolios
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  #we want all of the resource routes expect show. Changing show route to be singular not plural.
  #as: is renaming route name
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # default routes given to us:
  # get 'pages/home'
  # get 'pages/about'
  # get 'pages/contact'
  #changes the default routes to be more simple.
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  #default resource route
  #resources :blogs
  #we want to make it more custom
  resources :blogs do
    member do 
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
#whenever we create a new blog post, by default it is going to be in draft mode until it is published and the state changes.
class Blog < ApplicationRecord
    enum status: {draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged

    #data validation- a blog post must have a title and body in order to be created.
    validates_presence_of :title, :body, :topic_id

    belongs_to :topic

    has_many :comments, dependent: :destroy

    def self.recent
        order("created_at DESC")
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  #a controller process that allows a method to be run before other controller methods.
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  #show sidebar topics
  before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status]

  #says in the layout directory find a file called blog and apply layout styles. 
  layout "blog"
  #everyone has access to show and index. regular user cannot destroy, update, and create. site_admin can do everything.
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      #the .page(params[:page].per(5)) on Blog is part of the kaminiri gem which allows us to see only 5 blogs at one time.
      #recent is a method from blog.rb that places most recent blog posts first
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      # if not a site admin you will only see published blogs, not drafts.
      @blogs = Blog.published.recent.page(params[:page]).per(5)
    end
    #able to set a specific title for the blogs page using application controller method.
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      
    #page_title is a method from concerns/application file
    #we have access to @blog_title because of the before_action that calls :set_blog method.
    @page_title = @blog.title
    #search engine optimization. 
    @seo_keywords = @blog.body
    else  
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #if blog is a draft it changes it to published, otherwise it changes it to a draft.
  def toggle_status
    if @blog.draft?
    @blog.published! 
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def set_sidebar_topics
      @side_bar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderrayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true, 
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderrayified, options)
    markdown_to_html.render(text).html_safe
  end


  def blog_status_color blog
    if blog.draft?
      'color: red;'
    end
  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <nav class="breadcrumb blog-crumb">
    <%# blog helper provides method of blog_status_color %>
    <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) %> 
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %> 
    <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
    <%# shortcut that looks for a partial named blog (singular) because our instance variable is called blogs %>
    <%# this is a standard collection call %>
    <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
    <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %></p>
    
    <%= render partial: 'blogs/admin_actions', locals: {blog: blog } %>

    <p><%= blog.body %></p>
</div>

app/views/blogs/_form.html.erb
<%# partials are html files %>
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
    <%# alert_generator is from application/helper.rb  %>
    <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class='form-group'>
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class='form-group'>
    <%= f.label :topic_id %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                include_blank: true
                              },
                              class: 'form-control'
                            )
    %>
  </div>

  <div class='form-group'>
    <%= f.radio_button :status, 'draft' %>
    <%= f.label :status, 'Draft' %>

    <%= f.radio_button :status, 'published' %>
    <%= f.label :status, 'Published' %>
  </div>

  <div class='form-group'>
    <%= f.text_area :body, class: 'form-control', rows: '15', placeholder: "Content" %>
  </div>

  <div class='form-group'>
    <%# button has to have a name in order for bootstrap button styles to be applied  %>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">
    <h1>Editing Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Show', @blog %> 
    <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-md-8 blog-main">
  <%= render @blogs %>
  <%# paginate comes from kaminiri gem package. allows us to have next and last buttons. %>
  <%= paginate @blogs%>
</div>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
    <h1>New Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<%# Shows specific blog post %>
<div class="col-md-8 blog-main">
  <h2><%= @blog.title %></h2>

  <nav class="breadcrumb">
    <%= link_to "Home", root_path, class: 'breadcrumb-item' %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item' %>
    <span class='breadcrumb-item active'><%= @blog.title %></span>

    <p style='padding-left: 20px;'>
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin)%>
      <%= link_to fa_icon('trash'), @blog, method: :delete, data: {confirm: "Are you sure you want to delete this post?"} if logged_in?(:site_admin)%>
    </p>
  </nav>

  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %> 
  <%# markdown is a method from the blogs helper to allow us to use markdown language in our blog posts %>
  <p> <%= markdown(@blog.body) %> </p>

  <%= render 'comments/comment_form' %>
  
  <%# rendering a partial %>
  <div id='comments' data-blog-id='<%= @blog.id %>'>
    <%= render @blog.comments %>
  </div>
</div>