config/routes.rb
Rails.application.routes.draw do
  # after we ran a --   rails g controller Topics index show   it generated these routes
  # get 'topics/index'
  # get 'topics/show'

  # we are changing it to this route
  resources :topics, only: [:index, :show]

  devise_for :users
  # default routes given to us for resources  
  # resources :portfolios
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  #we want all of the resource routes expect show. Changing show route to be singular not plural.
  #as: is renaming route name
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # default routes given to us:
  # get 'pages/home'
  # get 'pages/about'
  # get 'pages/contact'
  #changes the default routes to be more simple.
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  #default resource route
  #resources :blogs
  #we want to make it more custom
  resources :blogs do
    member do 
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  #establishing connection with db technology table
  has_many :technologies

  #accepts multiple attributes
  #in terminal would type: 
  #Portfolio.create!(title: "Web app", substring: "It is awesome", body: "Some text", technologies_attributes: [{name: "Ruby"}, {name: "Angular"}, {name: "React.js"}])
  #do not accept this if the attribute of name from technologies db table if blank
  accepts_nested_attributes_for :technologies,
                                # allows us to delete technologies
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank?}

  #data validation- a portfolio must have a title, body, main_image, thumb_image in order to be created.
  validates_presence_of :title, :body

  #carrierwave gem helped provided this
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader


  #we are setting default values for the main_image and thumb_image for when a portofolio item has been initialized.
  # after_initialize :set_defaults

  #positions portfolio items in ascending order 
  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
#The controller has a direct line of communication with the view.
#When creating a controller from scratch, make sure the function name is the same as the views file name.


class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :destroy, :show]
  layout "portfolio"
  #everyone has access to show and index. regular user cannot destroy, update, and create. site_admin can do everything.
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  #index action shows all portfolio items in ascending order
  #@ symbol makes it an instance variable in order to access it in the views and controller file. 
  #if no @ symbol it will only be accessed in the method, not other files.
  def index 
    @portfolio_items = Portfolio.by_position
  end
  
  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    #tells Ruby that we are all done and that there is no view file for this method.
    render nothing: true
  end

  #new action only renders the item, it does not create it. 
  #@ allowed us to created a new instance of the portfolio and made it available to the form.
  def new 
    @portfolio_item = Portfolio.new
  end

  #create action creates a portfolio item
  def create
    #specifying the parameters that are allowed to go through the system.
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        #if the item is successfully created, portfolio_path leads to the full list of portfolio items.
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit 
  end
  
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end


  def show
  end


  def destroy
    #destroy/delete record
    @portfolio_item.destroy
    #redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was deleted' }
    end
  end

  #private is a way to organize our methods. private methods can only be used inside this specific class.
  private
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        # cocoon needs us to include an :id and :_destroy
                                        technologies_attributes: [:id, :name, :_destroy]
                                        )

  end
  
  def set_portfolio_item
    #perform the lookup
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://placehold.it/#{height}x#{width}"
  end  

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
    <%# alert_generator is from application/helper.rb  %>
    <%= alert_generator error %>
    <% end %>
  <% end %>

<div class='row'>
  <div class='col-md-6'>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :subtitle %>
      <%= f.text_area :subtitle, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label class='btn btn-primary'>
        Upload a main image file<%= f.file_field :main_image, style: 'display:none;' %>
      </label>
    </div>

    <div class="form-group">
      <label class='btn btn-primary'>
        Upload a thumb image file<%= f.file_field :thumb_image, style: 'display:none;' %>
      </label>
    </div>

  </div>

  <div class='col-md-6'>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', rows: 13 %>
    </div>
  </div>

  <div class='col-md-12'>
    <h2>Technologies Used: </h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
      
      <div>
        <%# link_to_add_association is a special method cacoon gives us %>
        <%= link_to_add_association 'Add Technology', f, :technologies%>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Items', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class='col-md-4'>
  <%# data-id is grabbing the specific portfolio item id for javascript file %>
  <div class="card" data-id="<%= portfolio_item.id%>">
    <%# portfolio_img tag comes from the method in app/helpers/portfolio_helper  %>
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
    <p class="card-text">
      <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></span> <%= portfolio_item.subtitle %>
    </p>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<%# need a class nested-fields for cocoon %>
<div class='form-group nested-fields'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%# link_to_remove_association is a special method cacoon gives us %>
  <%= link_to_remove_association 'Remove Tecnnology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class='container portfolio-form portfolio-container'>
  <h1>Edit Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item%>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin)  %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>" >
      <%# looking for a partial called portfolio. Since we named the partial portfolio_item we need to specify. %>
      <%# this is a manual collection call %>
      <%= render partial:  'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class='container portfolio-form'>
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item%>
</div>

app/views/portfolios/show.html.erb
<%-# What we want each specific portfolio item to show. -%>
<div class='container'>
  <div class='row portfolio-container'>
    <div class='col-md-7'>
      <%= image_tag portfolio_img(@portfolio_item.thumb_image, 'main'), width: '100%' %>
    </div>
    <div class='col-md-5'>
      <h1><%= @portfolio_item.title %></h1>
      
      <hr>

      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      
      <hr>

      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %> </p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div >
          <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
        </div>
      <% end %>

    </div>
  </div>
</div>