config/routes.rb
Rails.application.routes.draw do
  # after we ran a --   rails g controller Topics index show   it generated these routes
  # get 'topics/index'
  # get 'topics/show'

  # we are changing it to this route
  resources :topics, only: [:index, :show]

  devise_for :users
  # default routes given to us for resources  
  # resources :portfolios
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  #we want all of the resource routes expect show. Changing show route to be singular not plural.
  #as: is renaming route name
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # default routes given to us:
  # get 'pages/home'
  # get 'pages/about'
  # get 'pages/contact'
  #changes the default routes to be more simple.
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  #default resource route
  #resources :blogs
  #we want to make it more custom
  resources :blogs do
    member do 
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner">
        <p>@2019 | Kristina Hales | Full Stack Developer</p>
    </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
  <h3 class="masthead-brand">Kristina Hales</h3>
  <nav class="nav nav-masthead justify-content-center app-nav">
    <%= nav_helper 'nav-link', 'span' %>
    <%# Checks for current user from app/helper/application_helper %>
    <%= login_helper 'nav-link'%>
  </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-center align-items-center">
    
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">My Blog Posts</a>
    </div>

    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %> <%= link_to 'Topics', topics_path %>
    </span>
    
  </div>
</header>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Kristina Hales</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%# helpers/application_helper %>
      <%= nav_helper 'nav-link', 'span' %>  
      <%= login_helper 'nav-link' %>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
  <h4 class="font-italic">About</h4>
  <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class='sidebar-module'>
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%=link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-4">
  <h4 class="font-italic">Elsewhere</h4>
  <ol class="list-unstyled social-links">
    <li><a href="#"><%= fa_icon "github" %></a></li>
    <li><a href="#"><%= fa_icon "facebook" %></a></li>
    <li><a href="#"><%= fa_icon "twitter" %></a></li>
    <li><a href="#"><%= fa_icon "instagram" %></a></li>
  </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<%# Partials are always created in the views file and contain a _ before the name. %>
<%# We are able to access these nav bar components in more than one layout now. %>
<div class="<%= location %>">
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "About", about_path %></div>
    <div><%= link_to "Contact", contact_path %></div>
    <div><%= link_to "Blog", blogs_path %></div>
    <div><%= link_to "Portfolio", portfolios_path %></div>
    <%# This method checks for current user from app/helper/application_helper %>
    <%= login_helper 'nav-link' %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path%>/      
      <a href="#">Back to top</a>
    </p>
    <p>@2019 | Kristina Hales | Full Stack Developer</p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <%= link_to 'Find out more about me', about_path, class:"btn btn-primary" %>
      <%= link_to 'Blogs path', blogs_path, class:"btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Although I am new to the tech field, I love have a passion for web development. I absolutely love learning. What excites me most about this new career path it constantly pushes me to my limits and become better. I currently know React.js, Node, Javascript, Ruby, PostgreSQL, HTML5, and CSS3.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <%# Checks for current user from app/helper/application_helper %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

  <div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
      <strong>Kristina Hales</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>